//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Appointment
{
	public virtual DateTime Schedule
	{
		get;
		set;
	}

	public virtual bool ConsumerAlertEnabled
	{
		get;
		set;
	}

	public virtual bool ProviderAlertEnabled
	{
		get;
		set;
	}

	public virtual ServiceProvider AppointmentServiceProvider
	{
		get;
		set;
	}

	public virtual ServiceConsumer AppointmentServiceConsumer
	{
		get;
		set;
	}

	public virtual bool IsConfirmed
	{
		get;
		set;
	}

	public virtual Resource BookedResources
	{
		get;
		set;
	}

	public virtual bool IsRescheduled
	{
		get;
		set;
	}

	public virtual DateTime OldSchedule
	{
		get;
		set;
	}

	public virtual int AlertBefore
	{
		get;
		set;
	}

	public virtual bool IsCancelled
	{
		get;
		set;
	}

	public virtual Service AppointmentType
	{
		get;
		set;
	}

	public virtual Guid ConfirmationNumber
	{
		get;
		set;
	}

}

