//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ContactInfo
{
	public virtual string ContactNumber
	{
		get;
		set;
	}

	public virtual string FaxNumber
	{
		get;
		set;
	}

	public virtual string EmailAddress
	{
		get;
		set;
	}

	public virtual string DisplayName
	{
		get;
		set;
	}

	public virtual string MailAddress
	{
		get;
		set;
	}

}

