//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Customer
{
	public virtual string DisplayName
	{
		get;
		set;
	}

	public virtual string FullName
	{
		get;
		set;
	}

	public virtual int VisitFrequency
	{
		get;
		set;
	}

	public virtual ContactInfo Contact
	{
		get;
		set;
	}

	public virtual DateTime LastVisit
	{
		get;
		set;
	}

}

