//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// A resource can be a person, a room, a counter, a telephone, computer, etc.
/// </summary>
public class Resource
{
	public virtual string ResourceName
	{
		get;
		set;
	}

	public virtual ServiceProvider Owner
	{
		get;
		set;
	}

	public virtual ServiceProvider ServiceProvider
	{
		get;
		set;
	}

}

