//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ServiceConsumer
{
	public virtual ContactInfo Contact
	{
		get;
		set;
	}

	public virtual ServiceConsumerType ConsumerType
	{
		get;
		set;
	}

	public virtual Customer ServiceCustomer
	{
		get;
		set;
	}

}

